import { WorkoutTemplate } from '../../../models/workout-template';
import { Tag } from '../../../models/tag';
import {BodyPart, ExerciseCategory} from "../../../models/exercise";

export const tags: Tag[] = [
  { id: 1, name: 'Strength Training' },
  { id: 2, name: 'Cardio' },
  { id: 3, name: 'Flexibility' },
  { id: 4, name: 'Core' },
  { id: 5, name: 'Yoga' },
];

export const suggestedWorkoutTemplate: WorkoutTemplate = {
  id: 1,
  title: 'High-Intensity Interval Training',
  exercises: [
    {
      id: 1,
      name: 'Squats',
      sets: [
        {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: true,
        },
        {
          id: 2,
          reps: 7,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: true,
        },
      ],
      prSet: {
        id: 1,
        reps: 8,
        weight: 135,
        previousReps: 5,
        previousWeight: 120,
        completed: false,
      },
      bodyPart: BodyPart.BACK,
      category: ExerciseCategory.MACHINE,
    },
    {
      id: 2,
      name: 'Lunges',
      sets: [
        {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
      ],
      prSet: {
        id: 1,
        reps: 8,
        weight: 135,
        previousReps: 5,
        previousWeight: 120,
        completed: false,
      },
      bodyPart: BodyPart.BACK,
      category: ExerciseCategory.MACHINE,
    },
    {
      id: 3,
      name: 'Push-ups',
      sets: [
        {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
      ],
      prSet: {
        id: 1,
        reps: 8,
        weight: 135,
        previousReps: 5,
        previousWeight: 120,
        completed: false,
      },
      bodyPart: BodyPart.BACK,
      category: ExerciseCategory.MACHINE,
    },
    {
      id: 4,
      name: 'Pull-ups',
      sets: [
        {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
      ],
      prSet: {
        id: 1,
        reps: 8,
        weight: 135,
        previousReps: 5,
        previousWeight: 120,
        completed: false,
      },
      bodyPart: BodyPart.BACK,
      category: ExerciseCategory.MACHINE,
    },
  ],
  estimatedDuration: 30,
  totalSets: 5,
  lastPerformedWorkout: {
    id: 1,
    duration: '35 min',
    date: new Date('2024-07-18'),
  },
  tags: tags,
  volumeTrend: {
    value: 'increase',
    percentage: 10,
  },
};

export const workoutTemplates: WorkoutTemplate[] = [
  suggestedWorkoutTemplate,
  suggestedWorkoutTemplate,
  suggestedWorkoutTemplate,
  {
    id: 1,
    title: 'Back + Biceps',
    exercises: [
      {
        id: 1,
        name: 'Squats',
        sets: [
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: true,
          },
          {
            id: 2,
            reps: 7,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: true,
          },
          {
            id: 2,
            reps: 7,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: true,
          },
          {
            id: 2,
            reps: 7,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 2,
            reps: 7,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 2,
            reps: 7,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 2,
            reps: 7,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
        ],
        prSet: {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
        bodyPart: BodyPart.BACK,
        category: ExerciseCategory.MACHINE,
      },
      {
        id: 2,
        name: 'Lunges',
        sets: [
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
        ],
        prSet: {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
        bodyPart: BodyPart.BACK,
        category: ExerciseCategory.MACHINE,
      },
      {
        id: 3,
        name: 'Push-ups',
        sets: [
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
        ],
        prSet: {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
        bodyPart: BodyPart.BACK,
        category: ExerciseCategory.MACHINE,
      },
      {
        id: 4,
        name: 'Pull-ups',
        sets: [
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 2,
            reps: 7,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 2,
            reps: 7,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 2,
            reps: 7,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 2,
            reps: 7,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
        ],
        prSet: {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
        bodyPart: BodyPart.BACK,
        category: ExerciseCategory.MACHINE,
      },
      {
        id: 5,
        name: 'Pull-ups',
        sets: [
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
        ],
        prSet: {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
        bodyPart: BodyPart.BACK,
        category: ExerciseCategory.MACHINE,
      },
      {
        id: 6,
        name: 'Pull-ups',
        sets: [
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
        ],
        prSet: {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
        bodyPart: BodyPart.BACK,
        category: ExerciseCategory.MACHINE,
      },
      {
        id: 7,
        name: 'Pull-ups',
        sets: [
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
        ],
        prSet: {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
        bodyPart: BodyPart.BACK,
        category: ExerciseCategory.MACHINE,
      },
      {
        id: 7,
        name: 'Pull-ups',
        sets: [
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
          {
            id: 1,
            reps: 8,
            weight: 135,
            previousReps: 5,
            previousWeight: 120,
            completed: false,
          },
        ],
        prSet: {
          id: 1,
          reps: 8,
          weight: 135,
          previousReps: 5,
          previousWeight: 120,
          completed: false,
        },
        bodyPart: BodyPart.BACK,
        category: ExerciseCategory.MACHINE,
      },
    ],
    estimatedDuration: 30,
    totalSets: 5,
    lastPerformedWorkout: {
      id: 1,
      duration: '35 min',
      date: new Date('2024-07-18'),
    },
    tags: tags,
    volumeTrend: {
      value: 'increase',
      percentage: 10,
    },
  },
];
